In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
X=([0,0],[0,1],[1,0],[1,1])
x=np.array(X)
print(x)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [20]:
y=([0],[1],[1],[0])
Y=np.array(y)
print(Y)

[[0]
 [1]
 [1]
 [0]]


In [38]:
np.random.randn(42)
w1=np.random.randn(2,1)
b1=np.zeros(1)
print(w1)
print(b1)
#w2=np.random.randn(2,1)

[[0.95180125]
 [0.10306443]]
[0.]


In [39]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [45]:
def neuron(X,w1,b1):
    z=np.dot(X,w1)+b1;
    _pred=sigmoid(z);
    print(_pred)
    y_pred=np.round(_pred);
    return y_pred

In [46]:
output=neuron(X,w1,b1)
print(output)

[[0.5       ]
 [0.52574332]
 [0.72147728]
 [0.74170815]]
[[0.]
 [1.]
 [1.]
 [1.]]


In [48]:
def sigmoid_derivative(X):
    return X*(1-X)

In [49]:
lr = 0.05
epochs = 50000
n_samples = 4

In [52]:
for epoch in range(epochs):
    z1 = np.dot(X, w1) + b1         
    a1 = sigmoid(z1)
    
    #z2 = np.dot(a1, w2) + b2       
    #a2 = sigmoid(z2)
    
    loss = np.mean((y - a1)**2)
    error = -2 * (y - a1) / n_samples  
    
    d2 = error * sigmoid_derivative(a1)     
    #d1 = np.dot(d2, w2.T) * sigmoid_deriv(a1)  
    
    #w2 -= lr * np.dot(a1.T, d2)        
    #b2 -= lr * np.sum(d2, axis=0)      
    w1 -= lr * np.dot(np.array(X).T, d2)   
    b1 -= lr * np.sum(d2, axis=0)  # Shape becomes (1,)
  
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

print("Final Output:\n", np.round(a1))


Epoch 0, Loss: 0.2500
Epoch 100, Loss: 0.2500
Epoch 200, Loss: 0.2500
Epoch 300, Loss: 0.2500
Epoch 400, Loss: 0.2500
Epoch 500, Loss: 0.2500
Epoch 600, Loss: 0.2500
Epoch 700, Loss: 0.2500
Epoch 800, Loss: 0.2500
Epoch 900, Loss: 0.2500
Epoch 1000, Loss: 0.2500
Epoch 1100, Loss: 0.2500
Epoch 1200, Loss: 0.2500
Epoch 1300, Loss: 0.2500
Epoch 1400, Loss: 0.2500
Epoch 1500, Loss: 0.2500
Epoch 1600, Loss: 0.2500
Epoch 1700, Loss: 0.2500
Epoch 1800, Loss: 0.2500
Epoch 1900, Loss: 0.2500
Epoch 2000, Loss: 0.2500
Epoch 2100, Loss: 0.2500
Epoch 2200, Loss: 0.2500
Epoch 2300, Loss: 0.2500
Epoch 2400, Loss: 0.2500
Epoch 2500, Loss: 0.2500
Epoch 2600, Loss: 0.2500
Epoch 2700, Loss: 0.2500
Epoch 2800, Loss: 0.2500
Epoch 2900, Loss: 0.2500
Epoch 3000, Loss: 0.2500
Epoch 3100, Loss: 0.2500
Epoch 3200, Loss: 0.2500
Epoch 3300, Loss: 0.2500
Epoch 3400, Loss: 0.2500
Epoch 3500, Loss: 0.2500
Epoch 3600, Loss: 0.2500
Epoch 3700, Loss: 0.2500
Epoch 3800, Loss: 0.2500
Epoch 3900, Loss: 0.2500
Epoch 4000, 